### ISSUE TITLE
Instructions for how to build?

### ISSUE THREAD

**Issue by jessep** [Schmavery/refmt-web#1]
I want to play around with this but can't get it to build.  Any chance you can give explicit build instructions? 

Tried the following:
1) Just running `make`. Didn't work, looked at makefile, see it depends on website.cmo, website.ml files
2) Tried running `rebuild website.native` which I think would generate those files, and it failed with the following error:

```
jessep:refmt-web jessep$ rebuild website.native
+ /Users/jessep/.opam/4.02.3/bin/ocamlc.opt -c -pp refmt -o website.cmo -intf-suffix .rei -impl website.re
File "website.re", line 1, characters 16-29:
Error: Unbound module Lwt_js_events
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.

  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:

      true: -traverse
      <dir1> or <dir2>: traverse
```

I'm pretty sure this is me just not knowing what the standard process is for building ocaml/reason, but would appreciate any help.

**Comment by Schmavery** [comment]
Hey @jessep!
Thanks for taking a look.  I managed to get this working late one night and pushed without paying much attention to presentation, intending to come back later.
Right now this has an implicit dependency on a cma from a local fork of reason that I have, which probably explains why make isn't working.  website.cmo and website.ml probably aren't the problem, it's [reason.cma](https://github.com/Schmavery/refmt-web/blob/master/Makefile#L11).  I always intended to come back and clean this up but life got in the way.
I'll try to update the code to work with reason master, and failing that, at least push the reason.cma so that it will build and people can play with changing the UI.  I'd also like to transition this to using bucklescript if/when rebuild supports it.

**Comment by jessep** [comment]
Okay, thanks!

**Comment by Schmavery** [comment]
I'm going to come back to this and fix the dependencies to reason next week, but I'm really crammed until then.

For now, this should more or less build it:

``` bash
git clone https://github.com/Schmavery/refmt-web.git
opam install js_of_ocaml
cd refmt-web
make
```

Please let me know if there are any more problems and I'll see if we can stop syncing the cma asap :smile: 
Edit: I'll also add some instructions to the README at that point once the dependencies get all figured out.
Edit2: Not quite working yet...
Edit3: Should be working now.  Tested on another machine.

**Comment by jessep** [comment]
Okay, it built, thanks! Now I can play around with it.

Edit: Oops, nevermind, it didn't build. Anyway, don't worry about it. I realized that to hack on what I wanted to, I can just run your existing js and use the dom you create as my interface for conversion :) So I'm just programmatically filling the textarea with ocaml, triggering a keyup, and extracting reason code from second textarea. For the moment seems to work.

**Comment by Schmavery** [comment]
Sounds good enough for now.  Any chance you could give me the error that you get when you build?  I'd still like to fix this.

**Comment by jessep** [comment]
Sorry for the slow response. Here it is:

``` bash
jessep:reason jessep$ git clone https://github.com/Schmavery/refmt-web.git
^ACloning into 'refmt-web'...
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 25 (delta 2), reused 0 (delta 0), pack-reused 14
Unpacking objects: 100% (25/25), done.
Checking connectivity... done.
jessep:reason jessep$ opam install js_of_ocaml
[NOTE] Package js_of_ocaml is already installed (current version is 2.7).
jessep:reason jessep$ cd refmt-web/
jessep:refmt-web jessep$ make
ocamlfind ocamlc -c -pp refmt -g -package "js_of_ocaml,js_of_ocaml.ppx,compiler-libs.common,menhirLib,str,re.str,easy-format" -impl website.re 
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /Users/jessep/.opam/4.02.3/lib/ocaml, /Users/jessep/.opam/4.02.3/lib/ocaml/compiler-libs
File "website.re", line 22, characters 2-20:
Error: Unbound value Sys_js.update_file
make: *** [website.cmo] Error 2


```

**Comment by Schmavery** [comment]
@bsansouci you ran into this too, right?  Did you say that updating js_of_ocaml fixed it for you?

**Comment by bsansouci** [comment]
I updated js_of_ocaml and this error went away.

**Comment by jessep** [comment]
Okay, great, that worked. Thanks for all the help!
